repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.11
  hooks:
    - id: uv-lock
    - id: uv-export